using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZombieMarch
{
    public class RunTest
    {
        public string FillJunctionsTests()
        {
            return "40 541 40000";
            //return "30 81 50000";
            //return "10 16 10000";
        }

        public List<string> FillRoadTests()
        {
            List<string> entradas = new List<string>();

            // ---- case 1 ------------
            //entradas.Add("0 2");
            //entradas.Add("0 4");
            //entradas.Add("1 2");
            //entradas.Add("1 3");
            //entradas.Add("1 5");
            //entradas.Add("1 6");
            //entradas.Add("2 3");
            //entradas.Add("2 5");
            //entradas.Add("3 4");
            //entradas.Add("3 6");
            //entradas.Add("3 7");
            //entradas.Add("3 8");
            //entradas.Add("3 9");
            //entradas.Add("6 7");
            //entradas.Add("7 8");
            //entradas.Add("8 9");


            // ------ Case 4 -------

            entradas.Add("0 1");
            entradas.Add("0 2");
            entradas.Add("0 3");
            entradas.Add("0 4");
            entradas.Add("0 6");
            entradas.Add("0 7");
            entradas.Add("0 8");
            entradas.Add("0 10");
            entradas.Add("0 11");
            entradas.Add("0 12");
            entradas.Add("0 14");
            entradas.Add("0 16");
            entradas.Add("0 17");
            entradas.Add("0 18");
            entradas.Add("0 19");
            entradas.Add("0 20");
            entradas.Add("0 22");
            entradas.Add("0 25");
            entradas.Add("0 26");
            entradas.Add("0 27");
            entradas.Add("0 32");
            entradas.Add("0 34");
            entradas.Add("0 36");
            entradas.Add("0 37");
            entradas.Add("1 2");
            entradas.Add("1 6");
            entradas.Add("1 7");
            entradas.Add("1 8");
            entradas.Add("1 11");
            entradas.Add("1 16");
            entradas.Add("1 17");
            entradas.Add("1 18");
            entradas.Add("1 19");
            entradas.Add("1 20");
            entradas.Add("1 21");
            entradas.Add("1 23");
            entradas.Add("1 25");
            entradas.Add("1 26");
            entradas.Add("1 28");
            entradas.Add("1 30");
            entradas.Add("1 31");
            entradas.Add("1 32");
            entradas.Add("1 33");
            entradas.Add("1 38");
            entradas.Add("1 39");
            entradas.Add("2 5");
            entradas.Add("2 7");
            entradas.Add("2 8");
            entradas.Add("2 9");
            entradas.Add("2 10");
            entradas.Add("2 11");
            entradas.Add("2 12");
            entradas.Add("2 13");
            entradas.Add("2 14");
            entradas.Add("2 15");
            entradas.Add("2 16");
            entradas.Add("2 17");
            entradas.Add("2 18");
            entradas.Add("2 19");
            entradas.Add("2 20");
            entradas.Add("2 21");
            entradas.Add("2 22");
            entradas.Add("2 23");
            entradas.Add("2 24");
            entradas.Add("2 25");
            entradas.Add("2 27");
            entradas.Add("2 29");
            entradas.Add("2 30");
            entradas.Add("2 32");
            entradas.Add("2 34");
            entradas.Add("2 35");
            entradas.Add("2 36");
            entradas.Add("2 37");
            entradas.Add("2 39");
            entradas.Add("3 4");
            entradas.Add("3 5");
            entradas.Add("3 6");
            entradas.Add("3 7");
            entradas.Add("3 10");
            entradas.Add("3 11");
            entradas.Add("3 12");
            entradas.Add("3 13");
            entradas.Add("3 15");
            entradas.Add("3 16");
            entradas.Add("3 17");
            entradas.Add("3 18");
            entradas.Add("3 20");
            entradas.Add("3 21");
            entradas.Add("3 22");
            entradas.Add("3 23");
            entradas.Add("3 24");
            entradas.Add("3 25");
            entradas.Add("3 26");
            entradas.Add("3 28");
            entradas.Add("3 29");
            entradas.Add("3 30");
            entradas.Add("3 31");
            entradas.Add("3 32");
            entradas.Add("3 33");
            entradas.Add("3 34");
            entradas.Add("3 35");
            entradas.Add("3 37");
            entradas.Add("3 38");
            entradas.Add("4 6");
            entradas.Add("4 9");
            entradas.Add("4 11");
            entradas.Add("4 12");
            entradas.Add("4 13");
            entradas.Add("4 14");
            entradas.Add("4 15");
            entradas.Add("4 16");
            entradas.Add("4 17");
            entradas.Add("4 18");
            entradas.Add("4 19");
            entradas.Add("4 20");
            entradas.Add("4 22");
            entradas.Add("4 23");
            entradas.Add("4 25");
            entradas.Add("4 26");
            entradas.Add("4 30");
            entradas.Add("4 33");
            entradas.Add("4 34");
            entradas.Add("4 37");
            entradas.Add("4 38");
            entradas.Add("4 39");
            entradas.Add("5 6");
            entradas.Add("5 7");
            entradas.Add("5 9");
            entradas.Add("5 10");
            entradas.Add("5 11");
            entradas.Add("5 12");
            entradas.Add("5 13");
            entradas.Add("5 14");
            entradas.Add("5 15");
            entradas.Add("5 17");
            entradas.Add("5 18");
            entradas.Add("5 20");
            entradas.Add("5 21");
            entradas.Add("5 22");
            entradas.Add("5 25");
            entradas.Add("5 26");
            entradas.Add("5 27");
            entradas.Add("5 28");
            entradas.Add("5 29");
            entradas.Add("5 30");
            entradas.Add("5 31");
            entradas.Add("5 32");
            entradas.Add("5 33");
            entradas.Add("5 35");
            entradas.Add("5 36");
            entradas.Add("5 39");
            entradas.Add("6 8");
            entradas.Add("6 9");
            entradas.Add("6 10");
            entradas.Add("6 11");
            entradas.Add("6 14");
            entradas.Add("6 15");
            entradas.Add("6 17");
            entradas.Add("6 18");
            entradas.Add("6 20");
            entradas.Add("6 21");
            entradas.Add("6 22");
            entradas.Add("6 24");
            entradas.Add("6 27");
            entradas.Add("6 28");
            entradas.Add("6 29");
            entradas.Add("6 30");
            entradas.Add("6 31");
            entradas.Add("6 32");
            entradas.Add("6 33");
            entradas.Add("6 34");
            entradas.Add("6 36");
            entradas.Add("6 37");
            entradas.Add("6 38");
            entradas.Add("7 8");
            entradas.Add("7 9");
            entradas.Add("7 10");
            entradas.Add("7 11");
            entradas.Add("7 12");
            entradas.Add("7 14");
            entradas.Add("7 16");
            entradas.Add("7 17");
            entradas.Add("7 18");
            entradas.Add("7 20");
            entradas.Add("7 21");
            entradas.Add("7 22");
            entradas.Add("7 23");
            entradas.Add("7 24");
            entradas.Add("7 25");
            entradas.Add("7 26");
            entradas.Add("7 27");
            entradas.Add("7 28");
            entradas.Add("7 29");
            entradas.Add("7 31");
            entradas.Add("7 32");
            entradas.Add("7 33");
            entradas.Add("7 34");
            entradas.Add("7 36");
            entradas.Add("7 37");
            entradas.Add("7 38");
            entradas.Add("7 39");
            entradas.Add("8 9 ");
            entradas.Add("8 10");
            entradas.Add("8 11");
            entradas.Add("8 14");
            entradas.Add("8 15");
            entradas.Add("8 17");
            entradas.Add("8 19");
            entradas.Add("8 20");
            entradas.Add("8 22");
            entradas.Add("8 24");
            entradas.Add("8 25");
            entradas.Add("8 26");
            entradas.Add("8 27");
            entradas.Add("8 29");
            entradas.Add("8 30");
            entradas.Add("8 31");
            entradas.Add("8 32");
            entradas.Add("8 33");
            entradas.Add("8 34");
            entradas.Add("8 38");
            entradas.Add("9 10");
            entradas.Add("9 11");
            entradas.Add("9 12");
            entradas.Add("9 13");
            entradas.Add("9 14");
            entradas.Add("9 15");
            entradas.Add("9 17");
            entradas.Add("9 18");
            entradas.Add("9 19");
            entradas.Add("9 20");
            entradas.Add("9 21");
            entradas.Add("9 23");
            entradas.Add("9 25");
            entradas.Add("9 26");
            entradas.Add("9 27");
            entradas.Add("9 28");
            entradas.Add("9 29");
            entradas.Add("9 31");
            entradas.Add("9 32");
            entradas.Add("9 33");
            entradas.Add("9 34");
            entradas.Add("9 37");
            entradas.Add("9 38");
            entradas.Add("9 39");
            entradas.Add("10 13");
            entradas.Add("10 14");
            entradas.Add("10 16");
            entradas.Add("10 17");
            entradas.Add("10 19");
            entradas.Add("10 20");
            entradas.Add("10 21");
            entradas.Add("10 24");
            entradas.Add("10 25");
            entradas.Add("10 26");
            entradas.Add("10 27");
            entradas.Add("10 28");
            entradas.Add("10 29");
            entradas.Add("10 30");
            entradas.Add("10 31");
            entradas.Add("10 32");
            entradas.Add("10 35");
            entradas.Add("10 36");
            entradas.Add("10 38");
            entradas.Add("11 12");
            entradas.Add("11 13");
            entradas.Add("11 14");
            entradas.Add("11 15");
            entradas.Add("11 17");
            entradas.Add("11 18");
            entradas.Add("11 19");
            entradas.Add("11 20");
            entradas.Add("11 21");
            entradas.Add("11 25");
            entradas.Add("11 26");
            entradas.Add("11 27");
            entradas.Add("11 28");
            entradas.Add("11 29");
            entradas.Add("11 30");
            entradas.Add("11 31");
            entradas.Add("11 33");
            entradas.Add("11 34");
            entradas.Add("11 35");
            entradas.Add("11 36");
            entradas.Add("11 37");
            entradas.Add("11 39");
            entradas.Add("12 13");
            entradas.Add("12 14");
            entradas.Add("12 15");
            entradas.Add("12 16");
            entradas.Add("12 17");
            entradas.Add("12 18");
            entradas.Add("12 20");
            entradas.Add("12 21");
            entradas.Add("12 22");
            entradas.Add("12 24");
            entradas.Add("12 25");
            entradas.Add("12 26");
            entradas.Add("12 27");
            entradas.Add("12 28");
            entradas.Add("12 31");
            entradas.Add("12 33");
            entradas.Add("12 34");
            entradas.Add("12 35");
            entradas.Add("12 36");
            entradas.Add("12 37");
            entradas.Add("12 38");
            entradas.Add("12 39");
            entradas.Add("13 14");
            entradas.Add("13 15");
            entradas.Add("13 16");
            entradas.Add("13 17");
            entradas.Add("13 19");
            entradas.Add("13 21");
            entradas.Add("13 22");
            entradas.Add("13 23");
            entradas.Add("13 24");
            entradas.Add("13 25");
            entradas.Add("13 29");
            entradas.Add("13 30");
            entradas.Add("13 32");
            entradas.Add("13 33");
            entradas.Add("13 34");
            entradas.Add("13 35");
            entradas.Add("13 37");
            entradas.Add("13 38");
            entradas.Add("13 39");
            entradas.Add("14 15");
            entradas.Add("14 16");
            entradas.Add("14 17");
            entradas.Add("14 20");
            entradas.Add("14 21");
            entradas.Add("14 22");
            entradas.Add("14 25");
            entradas.Add("14 26");
            entradas.Add("14 28");
            entradas.Add("14 29");
            entradas.Add("14 30");
            entradas.Add("14 31");
            entradas.Add("14 32");
            entradas.Add("14 33");
            entradas.Add("14 34");
            entradas.Add("14 35");
            entradas.Add("14 36");
            entradas.Add("14 37");
            entradas.Add("14 38");
            entradas.Add("15 16");
            entradas.Add("15 17");
            entradas.Add("15 19");
            entradas.Add("15 20");
            entradas.Add("15 21");
            entradas.Add("15 22");
            entradas.Add("15 27");
            entradas.Add("15 28");
            entradas.Add("15 29");
            entradas.Add("15 31");
            entradas.Add("15 32");
            entradas.Add("15 33");
            entradas.Add("15 35");
            entradas.Add("15 37");
            entradas.Add("15 39");
            entradas.Add("16 18");
            entradas.Add("16 19");
            entradas.Add("16 22");
            entradas.Add("16 23");
            entradas.Add("16 25");
            entradas.Add("16 26");
            entradas.Add("16 29");
            entradas.Add("16 30");
            entradas.Add("16 32");
            entradas.Add("16 35");
            entradas.Add("16 37");
            entradas.Add("17 18");
            entradas.Add("17 19");
            entradas.Add("17 20");
            entradas.Add("17 21");
            entradas.Add("17 22");
            entradas.Add("17 23");
            entradas.Add("17 24");
            entradas.Add("17 25");
            entradas.Add("17 26");
            entradas.Add("17 29");
            entradas.Add("17 30");
            entradas.Add("17 31");
            entradas.Add("17 32");
            entradas.Add("17 35");
            entradas.Add("17 36");
            entradas.Add("17 37");
            entradas.Add("17 38");
            entradas.Add("17 39");
            entradas.Add("18 19");
            entradas.Add("18 20");
            entradas.Add("18 23");
            entradas.Add("18 24");
            entradas.Add("18 26");
            entradas.Add("18 27");
            entradas.Add("18 28");
            entradas.Add("18 29");
            entradas.Add("18 30");
            entradas.Add("18 31");
            entradas.Add("18 32");
            entradas.Add("18 33");
            entradas.Add("18 34");
            entradas.Add("18 35");
            entradas.Add("18 36");
            entradas.Add("18 39");
            entradas.Add("19 20");
            entradas.Add("19 21");
            entradas.Add("19 22");
            entradas.Add("19 23");
            entradas.Add("19 25");
            entradas.Add("19 28");
            entradas.Add("19 30");
            entradas.Add("19 32");
            entradas.Add("19 34");
            entradas.Add("19 39");
            entradas.Add("20 21");
            entradas.Add("20 23");
            entradas.Add("20 25");
            entradas.Add("20 26");
            entradas.Add("20 27");
            entradas.Add("20 32");
            entradas.Add("20 33");
            entradas.Add("20 34");
            entradas.Add("20 35");
            entradas.Add("20 36");
            entradas.Add("21 22");
            entradas.Add("21 23");
            entradas.Add("21 24");
            entradas.Add("21 25");
            entradas.Add("21 26");
            entradas.Add("21 27");
            entradas.Add("21 28");
            entradas.Add("21 29");
            entradas.Add("21 30");
            entradas.Add("21 31");
            entradas.Add("21 34");
            entradas.Add("21 35");
            entradas.Add("21 36");
            entradas.Add("21 38");
            entradas.Add("21 39");
            entradas.Add("22 25");
            entradas.Add("22 26");
            entradas.Add("22 27");
            entradas.Add("22 28");
            entradas.Add("22 30");
            entradas.Add("22 31");
            entradas.Add("22 32");
            entradas.Add("22 35");
            entradas.Add("22 37");
            entradas.Add("22 38");
            entradas.Add("23 24");
            entradas.Add("23 26");
            entradas.Add("23 27");
            entradas.Add("23 28");
            entradas.Add("23 30");
            entradas.Add("23 33");
            entradas.Add("23 35");
            entradas.Add("23 36");
            entradas.Add("23 37");
            entradas.Add("23 38");
            entradas.Add("24 25");
            entradas.Add("24 26");
            entradas.Add("24 29");
            entradas.Add("24 30");
            entradas.Add("24 31");
            entradas.Add("24 34");
            entradas.Add("24 35");
            entradas.Add("24 36");
            entradas.Add("24 37");
            entradas.Add("24 38");
            entradas.Add("24 39");
            entradas.Add("25 26");
            entradas.Add("25 27");
            entradas.Add("25 28");
            entradas.Add("25 29");
            entradas.Add("25 32");
            entradas.Add("25 33");
            entradas.Add("25 34");
            entradas.Add("25 35");
            entradas.Add("25 36");
            entradas.Add("25 37");
            entradas.Add("25 38");
            entradas.Add("26 27");
            entradas.Add("26 28");
            entradas.Add("26 29");
            entradas.Add("26 30");
            entradas.Add("26 31");
            entradas.Add("26 32");
            entradas.Add("26 35");
            entradas.Add("26 36");
            entradas.Add("26 37");
            entradas.Add("26 38");
            entradas.Add("27 28");
            entradas.Add("27 29");
            entradas.Add("27 31");
            entradas.Add("27 32");
            entradas.Add("27 37");
            entradas.Add("27 38");
            entradas.Add("28 30");
            entradas.Add("28 31");
            entradas.Add("28 32");
            entradas.Add("28 33");
            entradas.Add("28 34");
            entradas.Add("28 35");
            entradas.Add("28 36");
            entradas.Add("28 37");
            entradas.Add("28 38");
            entradas.Add("29 31");
            entradas.Add("29 33");
            entradas.Add("29 36");
            entradas.Add("29 37");
            entradas.Add("30 31");
            entradas.Add("30 32");
            entradas.Add("30 33");
            entradas.Add("30 37");
            entradas.Add("31 32");
            entradas.Add("31 33");
            entradas.Add("31 34");
            entradas.Add("31 36");
            entradas.Add("31 39");
            entradas.Add("32 33");
            entradas.Add("32 34");
            entradas.Add("32 35");
            entradas.Add("32 36");
            entradas.Add("32 37");
            entradas.Add("32 38");
            entradas.Add("32 39");
            entradas.Add("33 34");
            entradas.Add("33 36");
            entradas.Add("33 37");
            entradas.Add("34 35");
            entradas.Add("34 37");
            entradas.Add("34 38");
            entradas.Add("34 39");
            entradas.Add("35 37");
            entradas.Add("35 38");
            entradas.Add("36 38");
            entradas.Add("36 39");
            entradas.Add("37 38");
            entradas.Add("38 39");

            // ----- Case 5 --------
            #region case5

            /*
            entradas.Add("0 3");
            entradas.Add("0 4");
            entradas.Add("0 6");
            entradas.Add("0 7");
            entradas.Add("0 8");
            entradas.Add("0 9");
            entradas.Add("0 1");
            entradas.Add("0 1");
            entradas.Add("0 1");
            entradas.Add("0 2");
            entradas.Add("0 2");
            entradas.Add("0 2");
            entradas.Add("0 2");
            entradas.Add("1 3");
            entradas.Add("1 4");
            entradas.Add("1 6");
            entradas.Add("1 7");
            entradas.Add("1 1");
            entradas.Add("1 1");
            entradas.Add("1 2");
            entradas.Add("2 3");
            entradas.Add("2 5");
            entradas.Add("2 8");
            entradas.Add("2 1");
            entradas.Add("2 1");
            entradas.Add("2 1");
            entradas.Add("2 2");
            entradas.Add("3 4");
            entradas.Add("3 5");
            entradas.Add("3 9");
            entradas.Add("3 1");
            entradas.Add("4 5");
            entradas.Add("4 6");
            entradas.Add("4 1");
            entradas.Add("4 1");
            entradas.Add("4 1");
            entradas.Add("4 1");
            entradas.Add("4 1");
            entradas.Add("4 2");
            entradas.Add("5 8");
            entradas.Add("5 1");
            entradas.Add("5 1");
            entradas.Add("5 2");
            entradas.Add("6 7");
            entradas.Add("6 2");
            entradas.Add("6 2");
            entradas.Add("7 1");
            entradas.Add("7 1");
            entradas.Add("7 2");
            entradas.Add("7 2");
            entradas.Add("7 2");
            entradas.Add("7 2");
            entradas.Add("7 2");
            entradas.Add("8 9");
            entradas.Add("8 1");
            entradas.Add("8 1");
            entradas.Add("8 1");
            entradas.Add("8 2");
            entradas.Add("8 2");
            entradas.Add("8 2");
            entradas.Add("8 2");
            entradas.Add("9 1");
            entradas.Add("9 1");
            entradas.Add("9 1");
            entradas.Add("9 2");
            entradas.Add("9 2");
            entradas.Add("11 12");
            entradas.Add("11 13");
            entradas.Add("11 26");
            entradas.Add("11 27");
            entradas.Add("11 28");
            entradas.Add("12 24");
            entradas.Add("13 15");
            entradas.Add("13 17");
            entradas.Add("13 29");
            entradas.Add("14 18");
            entradas.Add("14 24");
            entradas.Add("15 19");
            entradas.Add("16 21");
            entradas.Add("22 26");
            entradas.Add("26 28");
            */
            #endregion


            return entradas;
        }

        public List<string> FillInitialZombiePopTests()
        {
            List<string> entradas = new List<string>();

            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");
            //entradas.Add("1");

            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");
            entradas.Add("3");

            return entradas;
        }

    }
}
